Models/Contexto.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;

namespace pruebamvc.Models
{
    public class Contexto : DbContext
    {
        public Contexto() : base("Conexion")
        {

        }
        public DbSet<Empleados> empleados { set; get; }
    }
}

Models/Empleados.cs
using Microsoft.SqlServer.Server;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace pruebamvc.Models
{
    public class Empleados
    {
        [Key] 
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name="Id:")]
        public int Id { set; get; }
        [Required(ErrorMessage ="Introduzca su nombre")]
        [Display (Name ="Primer nombre:")]
        public string Primernombre { set; get; }
        [Display(Name ="Segundo Nombre:")]
        public String Segundonombre { set; get; }
        [Display(Name ="Apellido paterno:")]
        public string Apellidopaterno { set; get; }
        [Display(Name ="Apellido materno:")]
        public string Apellidomaterno { set; get; }
        [Display(Name ="Fecha en que Nacio:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}",ApplyFormatInEditMode =true)]
        public DateTime Fechanacimiento { set; get; }
        [Display(Name ="Salario:")]
        [DataType(DataType.Currency)]
        public Decimal Sueldo { set; get; }
        [Display(Name ="Activo:")]
        public Boolean Activo { set; get; }

    }
}

Controllers/EmpleadosController.cs
using pruebamvc.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pruebamvc.Controllers
{
    public class EmpleadosController : Controller
    {
        Contexto contexto = new Contexto();

        // GET: Empleados
        public ActionResult Index()
        {
            IEnumerable<Empleados> empleados = contexto.empleados.ToList();
            return View(empleados);
            //return Json(empleados, JsonRequestBehavior.AllowGet);
        }
        public ActionResult crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Guardar(Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                var buscar = contexto.empleados.Find(empleados.Id);
                if (buscar == null)
                {
                    contexto.empleados.Add(empleados);
                    contexto.SaveChanges();
                }
                else
                {
                    contexto.Set<Empleados>().AddOrUpdate(empleados);
                    contexto.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult Editar(int? Id)
        {
            Empleados empleados = new Empleados();
            if (Id == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                empleados = contexto.empleados.FirstOrDefault(busqueda => busqueda.Id == Id);
            }
            return View(empleados);
        }
        public ActionResult Eliminar(int? Id)
        {
            Empleados empleados = new Empleados();
            if (Id == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                empleados = contexto.empleados.FirstOrDefault(buscar => buscar.Id == Id);
            }
            return View(empleados);
        }
        public ActionResult Confirmareliminacion(int? Id)
        {
            Empleados empleados = new Empleados();
            if (Id == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                empleados = contexto.empleados.FirstOrDefault(busca => busca.Id == Id);
                contexto.empleados.Remove(empleados);
                contexto.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pruebamvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Empleados/Crear.cshtml
@model pruebamvc.Models.Empleados
@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>
@using (Html.BeginForm("Guardar","Empleados",FormMethod.Post))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true);
    <div>
        @Html.HiddenFor(model=> model.Id,new { @Value=0})
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Primernombre)
        @Html.EditorFor(Model => Model.Primernombre)
        @Html.ValidationMessageFor(Model => Model.Primernombre)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Segundonombre)
        @Html.EditorFor(Model => Model.Segundonombre)
        @Html.ValidationMessageFor(Model => Model.Segundonombre)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Apellidopaterno)
        @Html.EditorFor(Model => Model.Apellidopaterno)
        @Html.ValidationMessageFor(Model => Model.Apellidopaterno)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Apellidomaterno)
        @Html.EditorFor(Model => Model.Apellidomaterno)
        @Html.ValidationMessageFor(Model => Model.Apellidomaterno)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Fechanacimiento)
        @Html.EditorFor(Model => Model.Fechanacimiento)
        @Html.ValidationMessageFor(Model => Model.Fechanacimiento)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Sueldo)
        @Html.EditorFor(Model => Model.Sueldo)
        @Html.ValidationMessageFor(Model => Model.Sueldo)
    </div>
    <div class="row">
        @Html.LabelFor(model => model.Activo)
        @Html.EditorFor(Model => Model.Activo)
        @Html.ValidationMessageFor(Model => Model.Activo)
    </div>
    <div>
        <input type="submit" value="Guardar" />
    </div>
}

Views/Empleados/Editar.cshtml
@model pruebamvc.Models.Empleados
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm("Guardar", "Empleados", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(empleados=>empleados.Id)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Primernombre)
        @Html.EditorFor(empleados=>empleados.Primernombre)
        @Html.ValidationMessageFor(empleados=>empleados.Primernombre)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Segundonombre)
        @Html.EditorFor(empleados=>empleados.Segundonombre)
        @Html.ValidationMessageFor(empleados=>empleados.Segundonombre)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Apellidopaterno)
        @Html.EditorFor(empleados=>empleados.Apellidopaterno)
        @Html.ValidationMessageFor(empleados=>empleados.Apellidopaterno)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Apellidomaterno)
        @Html.EditorFor(empleados=>empleados.Apellidomaterno)
        @Html.ValidationMessageFor(empleados=>empleados.Apellidomaterno)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Fechanacimiento)
        @Html.EditorFor(empleados=>empleados.Fechanacimiento, new { htmlAttributes = new { @type = "date" } })
        @Html.ValidationMessageFor(empleados=>empleados.Fechanacimiento)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Sueldo)
        @Html.EditorFor(empleados=>empleados.Sueldo)
        @Html.ValidationMessageFor(empleados=>empleados.Sueldo)
    </div>
    <div class="row">
        @Html.LabelFor(empleados=>empleados.Activo)
        @Html.EditorFor(empleados=>empleados.Activo)
        @Html.ValidationMessageFor(empleados=>empleados.Activo)
    </div>
    <div>
    <input type="submit" value="Guardar" />
    </div>
}

Views/Empleados/Eliminar.cshtml
@model pruebamvc.Models.Empleados
@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>
@using (Html.BeginForm("Confirmareliminacion", "Empleados", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(empleados => empleados.Id)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Primernombre)
        @Html.DisplayFor(empleados => empleados.Primernombre)
        @Html.ValidationMessageFor(empleados => empleados.Primernombre)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Segundonombre)
        @Html.DisplayFor(empleados => empleados.Segundonombre)
        @Html.ValidationMessageFor(empleados => empleados.Segundonombre)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Apellidopaterno)
        @Html.DisplayFor(empleados => empleados.Apellidopaterno)
        @Html.ValidationMessageFor(empleados => empleados.Apellidopaterno)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Apellidomaterno)
        @Html.DisplayFor(empleados => empleados.Apellidomaterno)
        @Html.ValidationMessageFor(empleados => empleados.Apellidomaterno)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Fechanacimiento)
        @Html.DisplayFor(empleados => empleados.Fechanacimiento, new { htmlAttributes = new { @type = "date" } })
        @Html.ValidationMessageFor(empleados => empleados.Fechanacimiento)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Sueldo)
        @Html.DisplayFor(empleados => empleados.Sueldo)
        @Html.ValidationMessageFor(empleados => empleados.Sueldo)
    </div>
    <div class="row">
        @Html.LabelFor(empleados => empleados.Activo)
        @Html.DisplayFor(empleados => empleados.Activo)
        @Html.ValidationMessageFor(empleados => empleados.Activo)
    </div>
    <div>
        <input type="submit" value="Confirmar Eliminacion" />
    </div>
}

Views/Empleados/Index.cshtml
@model IEnumerable<pruebamvc.Models.Empleados> 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@Html.ActionLink("Nuevo Empleado","Crear")
<table>
    <thead>
       <tr>
           <td>
               Primer nombre
           </td>
           <td>
               Segundo nombre
           </td>
           <td>
               Apellido paterno
           </td>
           <td>
               Apellido materno
           </td>
           <td>
               Fecha de nacimiento
           </td>
           <td>
               Sueldo
           </td>
           <td>
               Activo
           </td>
           <td>

           </td>
       </tr>
    </thead>
    <tbody>
        @foreach(var empleado in Model)
        {
        <tr>
            <td>
                @empleado.Primernombre
            </td>
            <td>
                @empleado.Segundonombre
            </td>
            <td>
                @empleado.Apellidopaterno
            </td>
            <td>
                @empleado.Apellidomaterno
            </td>
            <td>
                @empleado.Fechanacimiento
            </td>
            <td>
                @empleado.Sueldo
            </td>
            <td>
                @empleado.Activo
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { @Id = empleado.Id }, new { @class = "btn btn-primary" });
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Eliminar", new { @Id = empleado.Id }, new { @class = "btn btn-danger" });
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @section scripts {
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        }
</body>
</html>